const x = 10
console.clear()
try{
    x =2

}catch(err){
console.log(`Erro: ${err}`)
}